### ISSUE TITLE
最新版的Word2Vector 模型 怎么用

### ISSUE THREAD

**Issue by gxgeek** [jsksxs360/AHANLP#1]
下载了【模型】Google_word2vec_zhwiki1709_300d.bin
 然后用	vec.loadGoogleModel("~/Google_word2vec_zhwiki1709_300d.bin");
去 load 这个模型 报错，请问这个最新版的怎么用？ 以前的wiki_chinese_word2vec(Google).model 可以用，

**Comment by jsksxs360** [comment]
你好，

你可以在 `AHANLP\src\ahanlp.properties` 中修改模型的位置，然后通过 `AHANLP.wordSimilarity("猫", "狗")` 等 AHANLP 提供的方法计算相似度。

我测试过，新版的模型应该是可以使用的。如果你遇到问题，可以打印一下错误看看。

```
Word2Vec word2vec = new Word2Vec();
try {
    word2vec.loadGoogleModel("~/Google_word2vec_zhwiki1709_300d.bin");
} catch (IOException e) {
    e.printStackTrace();
}
```
