### ISSUE TITLE
SogouCA_mini链接失效

### ISSUE THREAD

**Issue by androip** [jsksxs360/AHANLP#4]
SogouCA_mini链接失效
![image](https://user-images.githubusercontent.com/8563089/111487782-98d4be00-8773-11eb-8977-2760a7625e1e.png)

大佬可否提供一个新的链接？

**Comment by jsksxs360** [comment]
你好！

百度真的有毒啊，这个都屏蔽，而且我自己都下载不了。

搜狗这个是公开的语料，可以直接去 [搜狗实验室](http://www.sogou.com/labs/) 下载，我只是做了一些预处理。

我直接传在[Github](https://github.com/jsksxs360/AHANLP/raw/master/SogouCA_mini.zip)里了，这个是mini版，就2M，只用于演示。
