### ISSUE TITLE
AHANLP_base-1.4 百度网盘被停用，无法下载

### ISSUE THREAD

**Issue by carli-cmnt** [jsksxs360/AHANLP#5]
AHANLP_base-1.4 百度网盘被停用，无法下载，可以提供其他下载方式么？

**Comment by jsksxs360** [comment]
你好，


已经补了链接。百度是真的傻逼，不知道这有啥敏感的。


https://github.com/jsksxs360/AHANLP/releases



| |
徐昇
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年06月25日 11:02 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | [jsksxs360/AHANLP] AHANLP_base-1.4 百度网盘被停用，无法下载 (Issue #5) |

AHANLP_base-1.4 百度网盘被停用，无法下载，可以提供其他下载方式么？
