### ISSUE TITLE
关于“语义相似度”的问题

### ISSUE THREAD

**Issue by 1271880639** [jsksxs360/AHANLP#7]
String s4 = "你长得真好看";
        String s5 = "你长得真难看";
       System.out.println("s4 | s5 : " + AHANLP.sentenceSimilarity(s4, s5));
       作者你好。请问这种句子，只差一字，意思截然相反，为什么测试出的语义相似度有0.8748179。如果想解决这种问题，应该怎么改进呢？

**Comment by jsksxs360** [comment]
你好，这有两方面原因。

首先是 Word2Vec 词向量本身存在局限性，某些情况下捕获的是词语之间的相关性，比如“好看”和“难看”两个词语的余弦相似度本身就高达0.61。

```java
System.out.println("猫 | 狗 : " + AHANLP.wordSimilarity("猫", "狗"));
System.out.println("好看 | 难看 : " + AHANLP.wordSimilarity("好看", "难看"));
```
```
猫 | 狗 : 0.79404336
好看 | 难看 : 0.6143075
```

其次，这里使用的是一种基于规则的计算方法，通过计算两个句子词语之间的相似度进行计算。详见：[https://github.com/jsksxs360/Word2Vec/issues/5](https://github.com/jsksxs360/Word2Vec/issues/5)
因此实际上并没有真正建模句子的语义，依然是基于词语相似度计算的。这种计算方法也存在一定的问题。
PS：如果简单使用词袋模型(BOW)，直接把句子中词语向量的均值作为句向量，这里算出的值会更高（约0.9）

如果可以，建议使用BERT等基于Transformer的模型对句子进行编码，再计算句子表示的余弦值会更好。
